version: 0.1

default:
  deploy:
    parameters: &defaults
      profile: sandbox
      region: eu-central-1
      capabilities: CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
      s3_bucket: sandbox-samclisourcebucket

dev:
  deploy:
    parameters:
      <<: *defaults
      stack_name: transform-dev
      s3_prefix: transform-dev
      parameter_overrides:
        - Environment=dev
        - RepositoryName=sandbox-model
        - SnowflakeSecretArn=tbd
        - KMSKeyArn=tbd
        - DbtDocsBucketStem=sandbox-dbt-docs
        - DbtDocsAccessToken=tbd

prod:
  deploy:
    parameters:
      <<: *defaults
      stack_name: transform-prod
      s3_prefix: transform-prod
      parameter_overrides:
        - Environment=prod
        - RepositoryName=sandbox-model
        - SnowflakeSecretArn=tbd
        - KMSKeyArn=tbd
        - DbtDocsBucketStem=sandbox-dbt-docs
        - DbtDocsAccessToken=tbd